FROM alpine:3.20

# Install required packages
RUN apk add --no-cache bash nginx nano wget tar ca-certificates shadow && \
    mkdir -p /run/nginx

# Configure nginx
COPY nginx-single.conf /etc/nginx/nginx.conf

# Prepare directories used by start script
RUN mkdir -p /etc/wireguard && \
    chmod 700 /etc/wireguard && \
    mkdir -p /data/wireguard-configs

# Copy start script
COPY start.sh /start.sh
RUN chmod +x /start.sh

ENTRYPOINT ["/start.sh"]

